landingpage/urls.py
from django.urls import path
from .views import index, post_status, profil_index, check_email, subscribe, list_subscribers

app_name = 'landingpage'

urlpatterns = [
    path('', index, name='landingpage'),
    path('post_status', post_status, name='post_status'),
    path('profil', profil_index, name='profil'),
    path('email-checker', check_email, name='check_email'),
    path('subscribe', subscribe, name='subscribe'),
    path('list-subscribers', list_subscribers, name='list_subscribers'),
]

list_buku/urls.py
from django.urls import path, include
from django.contrib.auth import views
from .views import index, books, logout_auth, add_fav, del_fav

app_name = 'list_buku'

urlpatterns = [
    path('', index, name='list_bukus'),
    path('books', books, name='books'),
    path('login', views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout-auth', logout_auth, name='logout-auth'),
    path('add_fav', add_fav, name='add_fav'),
    path('del_fav', del_fav, name='del_fav'),
]

ppw_tdd/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='list_buku/'), name='redirect-root'),
    path('admin/', admin.site.urls),
    path('auth', include('social_django.urls', namespace='social')),
    path('landingpage/', include('landingpage.urls')),
    path('list_buku/', include('list_buku.urls')),
]

landingpage/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class PostStatus(models.Model):
    datetime = models.DateTimeField(default=datetime.now())
    status = models.CharField(max_length=50)

class Subscriber(models.Model):
    nama = models.CharField(max_length=50)
    email = models.EmailField(unique=True, max_length=50)
    password = models.CharField(max_length=50)

list_buku/models.py
from django.db import models

# Create your models here.

landingpage/forms.py
from django import forms

class StatusForm(forms.Form):
    attrs = {
        'class': 'form-control',
        'rows': '5',
        'placeholder': 'Status Anda',
    }
    status = forms.CharField(label='', max_length=300, widget=forms.Textarea(attrs=attrs), required=True)

class SubscribeForm(forms.Form):
    attrs = {
        'class': 'form-control',
    }
    nama = forms.CharField(label='Nama', max_length=50, required=True, widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(label='Email', max_length=50, required=True, widget=forms.EmailInput(attrs=attrs))
    password = forms.CharField(label='Password', max_length=50, required=True, widget=forms.PasswordInput(attrs=attrs))

list_buku/forms.py
from django import forms

class SearchForm(forms.Form):
    keys = forms.CharField(label='Search', max_length=255, required=True, widget=forms.TextInput())

landingpage/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.http import HttpResponse
from .forms import StatusForm, SubscribeForm
from .models import PostStatus, Subscriber

# Create your views here.
status_list = PostStatus.objects.all()

def index(request):
    response = {'status_form': StatusForm, 'status_list': status_list[::-1]}
    return render(request, 'landingpage.html', response)

def post_status(request):
    form = StatusForm(request.POST or None)
    response = {}
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        new_status = PostStatus(status=response['status'])
        new_status.save()
        return HttpResponseRedirect('/landingpage')
    else:
        return HttpResponseRedirect('/landingpage')

def profil_index(request):
    response = {'form' : SubscribeForm}
    return render(request, 'profil.html', response)

def check_email(request):
    email = request.POST['email']
    db = Subscriber.objects.all()
    err = 'Email tersebut sudah pernah didaftarkan sebelumnya, silakan daftar dengan email lain'
    for data in db:
        if email == data.email:
            return JsonResponse({'message': err})
    return JsonResponse({'message': 'Ok'})

def subscribe(request):
    nama = request.POST['nama']
    email = request.POST['email']
    password = request.POST['password']
    Subscriber(nama=nama, email=email, password=password).save()
    return JsonResponse({'message': 'Data anda berhasil disimpan'})

def list_subscribers(request):
    subscribersjson = list()
    for i in Subscriber.objects.all():
        subscribersjson.append(i.nama)
    return JsonResponse({'subscribers' : subscribersjson})

list_buku/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .forms import SearchForm
import json
import requests

response = {}

def index(request):
    form = SearchForm
    response['form'] = form
    if request.user.is_authenticated:
        set_user_session(response, request)
    return render(request, 'daftar_buku.html', response)

def books(request):
    url = 'https://www.googleapis.com/books/v1/volumes?q='
    if 'search' in request.GET:
        url += request.GET['search']
    else:
        url += 'quilting'
    api = requests.get(url)
    books = api.json()
    for book in books['items']:
        book['volumeInfo']['star'] = 0
        if book['id'] in request.session['ch_book']:
            book['volumeInfo']['star'] = 1
    return JsonResponse(books)

def logout_auth(request):
    request.session.flush()
    return HttpResponseRedirect('/')

def set_user_session(response, request):
    if 'fav' not in request.session.keys():
        request.session['fav'] = 0
        request.session['ch_book'] = []
    response['fav'] = request.session['fav']
    response['ch_book'] = request.session['ch_book']

def add_fav(request):
    response = {}
    request.session['fav'] += 1;
    request.session['ch_book'].append(request.GET.get('id_buku'))
    response['fav'] = request.session['fav']
    return JsonResponse(response)

def del_fav(request):
    response = {}
    request.session['fav'] -= 1;
    request.session['ch_book'].remove(request.GET.get('id_buku'))
    response['fav'] = request.session['fav']
    return JsonResponse(response)

landingpage/templates/landingpage.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'landingpage/css/loading.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'landingpage/js/behaviour.js' %}"></script>
</head>

<body>
    <div class='loader'></div>

    <div class="jumbotron" id='header' style='background-color:#4bd1e6'>
        <h2 class="display-4">Hello, Apa kabar?</h2>
    </div>

    <div style='text-align: center'>
        <button type='button' id='changetheme' type='button' style='color:white; background-color:green;' class='btn btn-info' onclick='changeTheme()'>
        Change Theme</button>
    </div>

    <br>
    <div id="accordion" style='width: 50%; margin:auto'>
        <h3>Aktivitas</h3>
        <div>
            <ul>
                <li>Kuliah</li>
                <li>Ngoding</li>
                <li>Olahraga</li>
            </ul>
        </div>
        <h3>Organisasi dan Kepanitiaan</h3>
        <div>
            <ul>
                <li>FUKI Fasilkom UI</li>
                <li>Ristek Fasilkom UI</li>
                <li>Social Project Sospol FUKI</li>
            </ul>
        </div>
        <h3>Prestasi</h3>
        <div>
            <ul>
                <li>Finalist Vocompfest ICPC Provincial Contest</li>
                <li>Finalist Maranatha ICPC Provincial Contest</li>
                <li>Finalist ICPC Regional Asia Jakarta</li>
            </ul>
        </div>
    </div>

    <div style='margin:auto; padding: 10px; width: 50%'>
        <form id="form" method="POST" action="{% url 'landingpage:post_status' %}">
            {% csrf_token %}
            <div class="form-group">
                <h5>Update Status:</h5>
                {{ status_form }} 
            </div>
            <button id="profil" type="button" class="btn btn-info" type='submit' style='width:20%;float:left;'><a href="/landingpage/profil" style='text-decoration: none; color:white;'>My Profil</a></button>
            <div style='float:right'><button id="submit" form='form' class="btn btn-success">Post</button></div>
        </form>
        <br><br>
            {% for status in status_list %}
            <div class='card'>
                <div class='card-header' style='text-align: right; background-color:#4bd1e6; font-weight:bold'>
                    {{status.datetime|date:"l"}}, {{status.datetime}}
                </div>
                <div class='card-body'>
                    <p class='card-text'>{{status.status}}</p>
                </div>
            </div>
            <br>
            {% endfor %}
    </div>
</body>
</html>

landingpage/templates/profil.html
<!DOCTYPE html>
<html>
<head>
    <title>My Profile</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .nav.navbar-nav li a {
            color: white;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-default" style='background-color:#4bd1e6; font-size: 18px'>
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" style='color:black' href="#">Halo Apa Kabar?</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="#">Home</a></li>
                <li><a href="/landingpage">Status</a></li>
                <li><a href="/list_buku">Daftar Buku</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#form"><span class="glyphicon glyphicon-user"></span> Subscribe</a></li>
            </ul>
        </div>
    </nav>
    <h2 style="text-align:center">My Profile</h2>
    <div class='text-center' style='height: 90vh'>
        <img src="http://ppw-b-addffasilkom.herokuapp.com/static/profil/image.jpg" alt="Adli" style="width:30%; margin:auto">
        <h1 style='text-align:center'>Mohammad Adli</h1>
        <p style='text-align:center'>Saya seorang Mahasiswa Fakultas Ilmu Komputer dari Universitas Indonesia. Saya Merupakan programmer web junior. Ini merupakan website pertama saya. Enjoy it:)</p>
    </div>
    
    <div class='container' style='height: 100%;width: 100%;background-color: #4bd1e6;'>
        <br><br><br>
        <form id="form" method="POST">
            <h2 class='text-center'>Subscribe Me:</h2>
            <div class="form-group text-left" style='width:50%; margin: auto'>
                {% csrf_token %}
                <script type="text/javascript">
                    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
                </script>
                {{ form }} 
            </div>
        </form>
        <br>
        <div class='text-center'><button class='btn btn-success' disabled id='id_button'>Submit</button></div>
        <br><br>
        <div>
        <table class="table table-primary table-hover table-bordered" style="background-color: white">
            <thead class='text-center' style="background-color: white">
                <tr>
                    <th class='text-center'>Subscribers</th>
                    <th class='text-center'>Unsubscribe</th>
                </tr>
            </thead>
            <tbody id="list_subscribers">
            </tbody>
        </table>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript">

        show();
        function show() {    
            $.ajax({
                url: '/landingpage/list-subscribers',
                success: function(data) {
                    var output = '';
                    for(var i = 0; i <= data.subscribers.length; ++i) {
                        output += '<tr><td class="text-center"><b>' + data.subscribers[i] + '</b></td>';
                        output += "<td class='text-center'><button class='btn btn-danger'>Unsubscribe</button></td>" + '</tr>';
                    }
                    $('#list_subscribers').html(output);
                }
            });
            
            var xhr = new XMLHttpRequest();
            xhr.open(this.mehtod, this.url, true);
            xhr.setRequestHeader("X-CSRFToken", csrftoken);

            function csrfSafeMethod(method) {
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        }

        $('<p id="info_email" class="text-right"><b></b></p>').insertAfter('#id_email');
        $('<p></p>').insertAfter('#id_nama');
        
        $('#form').keyup(function(e){
            if(e.keyCode == 13) {
                $('#id_button').click();
            }
        })

        $('#id_button').click(function() {
            var nama = $('#id_nama');
            var email = $('#id_email');
            var password = $('#id_password');
            $.ajax({
                method: 'POST',
                url: '/landingpage/subscribe',
                data: { nama: nama.val(),
                        email: email.val(),
                        password: password.val()
                },
                success: function(msg) {
                    nama.val('');
                    email.val('');
                    password.val('');
                    $('#info_email b').html('');
                    alert(msg.message);
                    show();
                }
            })
        })

        function isEmail(email) {
            var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            return regex.test(email);
        }

        $('#id_email').keyup(function() {
            var email = $('#id_email').val();
            if(!isEmail(email)) {
                if(email === '') $('#info_email b').html('');
                else $('#info_email b').html('Format email tidak valid');
            } else {
                $.ajax({
                    method: "POST",
                    url : '/landingpage/email-checker',
                    data: { email: $('#id_email').val()},
                    success: function(msg) {
                        $('#info_email b').html(msg.message);
                    }
                });
            }
        });

        $('#id_nama, #id_email, #id_password').bind('keyup', function() {
            if(allFilled()) $('#id_button').removeAttr('disabled');
            else $('#id_button').attr('disabled', 'true');
        });

        function allFilled() {
            var filled = true;
            $('body input').each(function() {
                if($(this).val() == '') filled = false;
            });
            if(!isEmail($('#id_email').val()) || $('#info_email b').html() != 'Ok') filled = false;
            return filled;
        }

    </script>

</body>
</html>

list_buku/templates/daftar_buku.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Daftar Buku</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
    <div class="jumbotron" id='header' style='background-color:#4bd1e6'>
        <h2 class="display-4">Daftar Buku</h2>
    </div>

    {% if not user.is_authenticated %}
    <div class='text-center'>
        <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>
    </div>
    {% else %}
    <div class='text-center'>
        <h2>Selamat datang, {{user.first_name}} {{user.last_name}}</h2>
        <a href="{% url 'list_buku:logout-auth'%}">Logout</a>
    </div>
    <br>
    <div style='text-align: center'><h2 id='fav'>Jumlah favorit: {{fav}}</h2><div>

    <div class="col-lg-4 col-md-12">
        <div class="input-group">
            <input type="text" class="form-control" id="input_search">
            <div class="input-group-append">
                <button class="btn" id="search_button">Search</button>
            </div>
        </div>
    </div>

    <br>
    <table class="table table-primary table-hover table-bordered">
        <thead class='text-center' style="background-color: #4bd1e6">
            <tr>
                <th style='width: 12%'>Judul</th>
                <th style='width: 13%'>Info</th>
                <th style='width: 25%'>Derkripsi</th>
                <th style='width: 6%'>Favorite</th>
            </tr>
        </thead>
        <tbody id='list_buku'>
        </tbody>
    </table>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript">

        var total = 0;
        var stars_on = '/static/list_buku/stars_on.png';
        var stars_off = '/static/list_buku/stars_off.png'

        function show(books) {
            var books_now = "";
            if(!books.items) {
                $('#fav').html('Not Found');
                return;
            }
            for(var id = 1; id <= books.items.length; ++id) {
                var book = books.items[id-1]['volumeInfo'];
                var col1 = "<td class='text-center'>";
                var col2 = "<td class='text-left'>";
                var col3 = "<td class='text-justify'>";
                var col4 = "<td class='text-center'>";
                var stid = books.items[id-1]['id'];
                var na = 'Tidak Diketahui';
                var no = 'Tidak Ada Derkripsi';

                if(book['imageLinks']) {
                    col1 += "<img src='" + book['imageLinks']['thumbnail'] + "'><br>";
                } else {
                    col1 += "<img src='' alt='unkown'><br>";
                }
                col1 += "<b>" + (book['title'] ? book['title'] : na) + "</b></td>";

                col2 += "<p><b>Penulis</b> : " + (book['authors'] ? book['authors'] : na) + "</p>";
                col2 += "<p><b>Penerbit</b> : " + (book['publisher'] ? book['publisher'] : na) + "</p>";
                col2 += "<p><b>Tahun Terbit</b> : " + (book['publishedDate'] ? book['publishedDate'] : na) + "</p></td>";

                col3 += (book['description'] ? book['description'] : no) + "</td>";

                if(book['star'] == 1) col4 += "<img id='" + stid + "' src='" + stars_on + "'";
                else col4 += "<img id='" + stid + "' src='" + stars_off + "'";
                stid = '"' + stid + '"';
                col4 += "style='width:25%' onclick='fav("+ stid +")'></td>";

                books_now += "<tr>" + col1 + col2 + col3 + col4 + "</tr>";
            }
            $('#list_buku').html(books_now);
        }

        $.ajax({
            url: '/list_buku/books',
            success: function(books) {
                show(books);       
            }
        });

        $('#search_button').click(function() {
            var target = '/list_buku/books?search=' + $('#input_search').val();
            $.ajax({
                url: target,
                success: function(books) {
                    show(books);
                }
            })
        });

        function fav(id) {
            var now = $('#' + id);
            if(now[0].src.includes(stars_off)) {
                $.ajax({
                    url: '/list_buku/add_fav',
                    data: {id_buku:id},
                    success: function(res) {
                        total = res.fav;
                        now[0].src = stars_on;
                        $('#fav').html('Jumlah favorit: ' + total);
                    }
                })
            } else {
                $.ajax({
                    url: '/list_buku/del_fav',
                    data: {id_buku:id},
                    success: function(res) {
                        total = res.fav;
                        now[0].src = stars_off;
                        $('#fav').html('Jumlah favorit: ' + total);
                    }
                })
            }
            $('#fav').html('Jumlah favorit: ' + total);
        }

    </script>
    {% endif %}

</body>
</html>

list_buku/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-signin-client_id" content="619733070415-3smgteagjfpu35ci1siutcltb0v1edcs.apps.googleusercontent.com">
    <title>Daftar Buku</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
    <div class="g-signin2" data-onsuccess="onSignIn"></div>
    <a href="#" onclick="signOut();">Sign out</a>
    <script>
    </script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <script type="text/javascript">
        function onSignIn(googleUser) {
          var profile = googleUser.getBasicProfile();
          console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
          console.log('Name: ' + profile.getName());
          console.log('Image URL: ' + profile.getImageUrl());
          console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
        }

        function signOut() {
          var auth2 = gapi.auth2.getAuthInstance();
          auth2.signOut().then(function () {
                console.log('User signed out.');
            });
        }
    </script>
</body>
</html>